import { MemoryPattern, Transaction } from './store';
import { generateMockAddress, generateMockTxHash } from './utils';

export const mockPatterns: MemoryPattern[] = [
  {
    id: 'pattern-1',
    name: 'Liquidity Drain Pattern',
    description: 'Sequence of permission grants followed by small test transactions before major withdrawal',
    riskScore: 0.89,
    occurrences: 1247,
    lastSeen: Date.now() - 3600000,
    category: 'drain',
    sequence: [
      'Permission Grant',
      'Small Test Transfer',
      'Contract Interaction',
      'Liquidity Removal',
      'Final Drain',
    ],
  },
  {
    id: 'pattern-2',
    name: 'Flash Loan Exploit',
    description: 'Classic flash loan attack pattern with price manipulation',
    riskScore: 0.95,
    occurrences: 342,
    lastSeen: Date.now() - 7200000,
    category: 'exploit',
    sequence: [
      'Flash Loan Initiation',
      'Price Manipulation',
      'Collateral Deposit',
      'Excessive Borrow',
      'Loan Repayment',
    ],
  },
  {
    id: 'pattern-3',
    name: 'Governance Attack Setup',
    description: 'Token accumulation pattern before governance proposal manipulation',
    riskScore: 0.72,
    occurrences: 89,
    lastSeen: Date.now() - 86400000,
    category: 'governance',
    sequence: [
      'Token Accumulation',
      'Delegation Setup',
      'Proposal Submission',
      'Vote Manipulation',
      'Execution',
    ],
  },
  {
    id: 'pattern-4',
    name: 'Rug Pull Indicators',
    description: 'Developer wallet behavior consistent with exit scam preparation',
    riskScore: 0.91,
    occurrences: 567,
    lastSeen: Date.now() - 1800000,
    category: 'rug_pull',
    sequence: [
      'Liquidity Addition',
      'Marketing Spike',
      'Wallet Concentration',
      'Liquidity Removal',
      'Token Dump',
    ],
  },
  {
    id: 'pattern-5',
    name: 'Safe DeFi Interaction',
    description: 'Standard verified protocol interaction pattern',
    riskScore: 0.12,
    occurrences: 458293,
    lastSeen: Date.now() - 60000,
    category: 'safe',
    sequence: [
      'Wallet Connection',
      'Token Approval',
      'Swap/Deposit',
      'Confirmation',
    ],
  },
  {
    id: 'pattern-6',
    name: 'Sandwich Attack',
    description: 'MEV bot front-running and back-running pattern',
    riskScore: 0.67,
    occurrences: 23847,
    lastSeen: Date.now() - 300000,
    category: 'exploit',
    sequence: [
      'Mempool Detection',
      'Front-run Transaction',
      'Victim Transaction',
      'Back-run Transaction',
    ],
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: 'tx-1',
    hash: generateMockTxHash(),
    from: generateMockAddress(),
    to: generateMockAddress(),
    value: '2.5',
    timestamp: Date.now() - 120000,
    status: 'success',
    riskScore: 0.15,
    matchedPatterns: ['pattern-5'],
    type: 'swap',
  },
  {
    id: 'tx-2',
    hash: generateMockTxHash(),
    from: generateMockAddress(),
    to: generateMockAddress(),
    value: '0.1',
    timestamp: Date.now() - 300000,
    status: 'success',
    riskScore: 0.72,
    matchedPatterns: ['pattern-1'],
    type: 'approve',
  },
  {
    id: 'tx-3',
    hash: generateMockTxHash(),
    from: generateMockAddress(),
    to: generateMockAddress(),
    value: '15.0',
    timestamp: Date.now() - 600000,
    status: 'pending',
    riskScore: 0.45,
    matchedPatterns: [],
    type: 'transfer',
  },
  {
    id: 'tx-4',
    hash: generateMockTxHash(),
    from: generateMockAddress(),
    to: generateMockAddress(),
    value: '100.0',
    timestamp: Date.now() - 900000,
    status: 'success',
    riskScore: 0.88,
    matchedPatterns: ['pattern-2', 'pattern-6'],
    type: 'stake',
  },
  {
    id: 'tx-5',
    hash: generateMockTxHash(),
    from: generateMockAddress(),
    to: generateMockAddress(),
    value: '5.25',
    timestamp: Date.now() - 1200000,
    status: 'failed',
    riskScore: 0.92,
    matchedPatterns: ['pattern-4'],
    type: 'bridge',
  },
];

export const mockStats = {
  riskDistribution: [
    { name: 'Low Risk', value: 65, color: '#00ff88' },
    { name: 'Medium Risk', value: 25, color: '#ff8800' },
    { name: 'High Risk', value: 10, color: '#ff3366' },
  ],
  patternCategories: [
    { name: 'Exploit', count: 342, trend: 12 },
    { name: 'Rug Pull', count: 567, trend: -8 },
    { name: 'Drain', count: 1247, trend: 23 },
    { name: 'Governance', count: 89, trend: 5 },
    { name: 'Safe', count: 458293, trend: 156 },
  ],
  timelineData: [
    { date: '2025-07', patterns: 120, transactions: 15000, threats: 45 },
    { date: '2025-08', patterns: 156, transactions: 18500, threats: 62 },
    { date: '2025-09', patterns: 189, transactions: 22000, threats: 78 },
    { date: '2025-10', patterns: 234, transactions: 28000, threats: 95 },
    { date: '2025-11', patterns: 278, transactions: 35000, threats: 112 },
    { date: '2025-12', patterns: 312, transactions: 42000, threats: 134 },
  ],
  networkActivity: Array.from({ length: 24 }, (_, i) => ({
    hour: i,
    transactions: Math.floor(Math.random() * 5000) + 1000,
    risk: Math.random() * 0.5 + 0.1,
  })),
  chainDistribution: [
    { chain: 'Ethereum', transactions: 4500000, percentage: 45 },
    { chain: 'Polygon', transactions: 2200000, percentage: 22 },
    { chain: 'Arbitrum', transactions: 1500000, percentage: 15 },
    { chain: 'Optimism', transactions: 1000000, percentage: 10 },
    { chain: 'Base', transactions: 800000, percentage: 8 },
  ],
  memoryDepth: [
    { depth: '1 week', memories: 12000 },
    { depth: '1 month', memories: 45000 },
    { depth: '3 months', memories: 120000 },
    { depth: '6 months', memories: 280000 },
    { depth: '1 year', memories: 580000 },
    { depth: '2 years', memories: 1200000 },
  ],
};

export const mockPermissions = [
  {
    id: 'perm-1',
    name: 'Transaction Simulation',
    description: 'Allow MOSYNE to simulate transactions before execution',
    granted: true,
    icon: '🔍',
  },
  {
    id: 'perm-2',
    name: 'Historical Analysis',
    description: 'Access to analyze transaction history patterns',
    granted: true,
    icon: '📊',
  },
  {
    id: 'perm-3',
    name: 'Risk Alerts',
    description: 'Receive warnings for high-risk transactions',
    granted: true,
    icon: '⚠️',
  },
  {
    id: 'perm-4',
    name: 'Pattern Matching',
    description: 'Match transactions against known exploit patterns',
    granted: false,
    icon: '🧬',
  },
  {
    id: 'perm-5',
    name: 'Auto-Block High Risk',
    description: 'Automatically pause transactions matching critical patterns',
    granted: false,
    icon: '🛡️',
  },
];
